
// This file has been generated by the GUI designer. Do not modify.
namespace Game
{
	public partial class GameWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label labelTime;

		private global::Gtk.Label labelScore;

		private global::Gtk.DrawingArea drawingarea;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Game.GameWindow
			this.Name = "Game.GameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("GameWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Game.GameWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelTime = new global::Gtk.Label();
			this.labelTime.Name = "labelTime";
			this.labelTime.LabelProp = global::Mono.Unix.Catalog.GetString("Время:");
			this.hbox1.Add(this.labelTime);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelTime]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelScore = new global::Gtk.Label();
			this.labelScore.Name = "labelScore";
			this.labelScore.LabelProp = global::Mono.Unix.Catalog.GetString("Счёт:");
			this.hbox1.Add(this.labelScore);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelScore]));
			w2.Position = 1;
			w2.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.drawingarea = new global::Gtk.DrawingArea();
			this.drawingarea.Name = "drawingarea";
			this.vbox1.Add(this.drawingarea);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.drawingarea]));
			w4.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 578;
			this.DefaultHeight = 601;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingAreaExposeEvent);
		}
	}
}
