
// This file has been generated by the GUI designer. Do not modify.
namespace Game
{
	public partial class GameOverWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label5;

		private global::Gtk.Label labelScore;

		private global::Gtk.Button buttonBack;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Game.GameOverWindow
			this.Name = "Game.GameOverWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("GameOverWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Game.GameOverWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Конец игры");
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelScore = new global::Gtk.Label();
			this.labelScore.Name = "labelScore";
			this.vbox2.Add(this.labelScore);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelScore]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonBack = new global::Gtk.Button();
			this.buttonBack.CanFocus = true;
			this.buttonBack.Name = "buttonBack";
			this.buttonBack.UseUnderline = true;
			this.buttonBack.Label = global::Mono.Unix.Catalog.GetString("Главное меню");
			this.vbox2.Add(this.buttonBack);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonBack]));
			w3.Position = 2;
			w3.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.buttonBack.Clicked += new global::System.EventHandler(this.OnButtonBackClicked);
		}
	}
}
