
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label7;

	private global::Gtk.Button buttonPlay;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Меняй квадраты местами, чтобы взорвать их. У тебя есть одна минута. Вперёд!");
		this.vbox5.Add(this.label7);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label7]));
		w1.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.buttonPlay = new global::Gtk.Button();
		this.buttonPlay.CanFocus = true;
		this.buttonPlay.Name = "buttonPlay";
		this.buttonPlay.UseUnderline = true;
		this.buttonPlay.BorderWidth = ((uint)(78));
		this.buttonPlay.Label = global::Mono.Unix.Catalog.GetString("Играть");
		this.vbox5.Add(this.buttonPlay);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.buttonPlay]));
		w2.Position = 1;
		w2.Fill = false;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 493;
		this.DefaultHeight = 272;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.vbox5.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonPlay.Clicked += new global::System.EventHandler(this.OnButtonPlayClicked);
	}
}
